Deprecate Travis CI support
ember-cli/ember-cli pull request #10350
Opened 2023-08-21 15:03 UTC by bertdeblock

Implements https://github.com/emberjs/rfcs/pull/918.

Example:

<img width="1512" alt="Screenshot 2023-08-21 at 16 48 46 (2)" src="https://github.com/ember-cli/ember-cli/assets/7403183/1da3865b-a647-4010-99b3-b211ab01d383">

2023-08-28 17:39 UTC, locks requested changes

2023-08-28 17:39 UTC, locks commented on blueprints/addon/files/.travis.yml
> +# URL    https://deprecations.emberjs.com/ember-cli/v5.x#TODO
```suggestion
# URL    http://deprecations.emberjs.com/id/travis-ci-support
```

2023-08-28 17:39 UTC, locks commented on blueprints/app/files/.travis.yml
> +# URL    https://deprecations.emberjs.com/ember-cli/v5.x#TODO
```suggestion
# URL    http://deprecations.emberjs.com/id/travis-ci-support
```

2023-08-28 17:39 UTC, locks commented on lib/commands/init.js
> +          url: 'https://deprecations.emberjs.com/ember-cli/v5.x#TODO',
```suggestion
          url: 'http://deprecations.emberjs.com/id/travis-ci-support',
```

2023-08-28 17:39 UTC, locks commented on tests/fixtures/addon/defaults-travis/.travis.yml
> +# URL    https://deprecations.emberjs.com/ember-cli/v5.x#TODO
```suggestion
# URL    http://deprecations.emberjs.com/id/travis-ci-support
```

2023-08-28 17:39 UTC, locks commented on tests/fixtures/addon/yarn/.travis.yml
> +# URL    https://deprecations.emberjs.com/ember-cli/v5.x#TODO
```suggestion
# URL    http://deprecations.emberjs.com/id/travis-ci-support
```

2023-08-28 17:39 UTC, locks commented on tests/fixtures/app/npm-travis/.travis.yml
> +# URL    https://deprecations.emberjs.com/ember-cli/v5.x#TODO
```suggestion
# URL    http://deprecations.emberjs.com/id/travis-ci-support
```

2023-08-28 17:39 UTC, locks commented on tests/fixtures/app/with-blueprint-override-lint-fail/.travis.yml
> +# URL    https://deprecations.emberjs.com/ember-cli/v5.x#TODO
```suggestion
# URL    http://deprecations.emberjs.com/id/travis-ci-support
```

2023-08-28 17:39 UTC, locks commented on tests/fixtures/app/yarn-travis/.travis.yml
> +# URL    https://deprecations.emberjs.com/ember-cli/v5.x#TODO
```suggestion
# URL    http://deprecations.emberjs.com/id/travis-ci-support
```

2023-08-28 17:39 UTC, locks commented
Opened a PR so we can get a good idea of the final link: https://github.com/ember-learn/deprecation-app/pull/1338.

2023-09-07 19:06 UTC, kategengler commented on blueprints/addon/files/.travis.yml
> +# URL    https://deprecations.emberjs.com/ember-cli/v5.x#TODO
https seems to work

2023-09-07 19:07 UTC, kategengler approved these changes
lgtm pending url updates

2023-10-13 18:16 UTC, ef4 commented
The RFC for this is now Ready to Release, so this can be released and should be reported back on https://github.com/emberjs/rfcs/pull/978

2023-10-20 16:38 UTC, merged