[ENHANCEMENT] Vanilla Prettier setup in blueprints [RFC 1055]
ember-cli/ember-cli pull request #10596
Opened 2024-12-28 11:18 UTC by bertdeblock

2024-12-28 11:20 UTC, bertdeblock commented on tests/acceptance/smoke-test-slow.js
> -  it('eslint passes after running ember new', async function () {
Removed, because https://github.com/ember-cli/ember-cli/pull/10586 covers everything (ESLint, Stylelint, TypeScript, ...)

2025-01-06 11:45 UTC, bertdeblock commented on blueprints/app/files/package.json
>      "lint:fix": "concurrently \"<%= packageManager %>:lint:*:fix\" --names \"fix:\" --prefixColors auto",
```suggestion
    "lint:fix": "concurrently \"<%= packageManager %>:lint:*:fix\" --names \"fix:\" --prefixColors auto && <%= invokeScriptPrefix %> format",
```

2025-01-06 15:25 UTC, bertdeblock commented on blueprints/app/files/tests/index.html
> +    <!-- prettier-ignore -->
Prevents:

```
{{content-for "head"}} {{content-for "test-head"}}
```

2025-01-06 15:25 UTC, bertdeblock commented on blueprints/app/files/.prettierignore
> +/config/ember-cli-update.json
Both additions are generated files.

2025-01-10 19:37 UTC, ef4 requested changes
Suggested alternative: can we put `**/*.html` in the prettierignore?

Because the formatting prettier is producing here is not great. You were forced to add the special prettier-ignore comment line. And prettier is making several tags self-closing that are not actually supposed to be self-closing in the HTML spec.

The current blueprint doesn't do prettier formatting for html, so this is not a loss of existing functionality.

Separate question: is this introducing prettier formatting to markdown, and if so does it also rewrite people's READMEs? If so, that would possibly be another extension to ignore.

2025-01-16 16:43 UTC, NullVoxPopuli commented
hbs / gjs / etc are not explicitly HTML tho -- and this goes for jsx, vue, svelte, ng / angular, it's all shorthand to (eventually) generate HTML.

the HTML file is the only real HTML we have.

2025-01-16 16:57 UTC, mansona commented
apparently there is a plugin that fixes the issue? https://github.com/prettier/prettier/issues/15336#issuecomment-2509738565

2025-01-16 16:58 UTC, bertdeblock commented
I'm only saying that formatting-wise the same issue occurs in hbs, gjs, ...

2025-01-16 17:01 UTC, bertdeblock commented
Indeed, but I didn't really want to include yet another dependency in the blueprint. I would prefer to just follow Prettier. To me, that's kind of the point of using Prettier. Let it decide what's best readability/formatting wise.

2025-01-16 17:07 UTC, mansona commented
I agree with the point of prettier (I may not like it but I agree with what it's trying to do)... but in this case it's just wrong 🤔 Void elements are not and should not be "self closing"

2025-01-16 17:09 UTC, mansona commented
https://html.spec.whatwg.org/multipage/syntax.html#start-tags

> Then, if the element is one of the [void elements](https://html.spec.whatwg.org/multipage/syntax.html#void-elements), or if the element is a [foreign element](https://html.spec.whatwg.org/multipage/syntax.html#foreign-elements), then there may be a single U+002F SOLIDUS character (/), which on [foreign elements](https://html.spec.whatwg.org/multipage/syntax.html#foreign-elements) marks the start tag as self-closing. On [void elements](https://html.spec.whatwg.org/multipage/syntax.html#void-elements), it does not mark the start tag as self-closing but instead is unnecessary and has no effect of any kind. For such void elements, it should be used only with caution — especially since, if directly preceded by an [unquoted attribute value](https://html.spec.whatwg.org/multipage/syntax.html#unquoted), it becomes part of the attribute value rather than being discarded by the parser.

2025-01-16 18:12 UTC, SergeAstapov commented
if another vote matters, I agree with @mansona that Prettier is surely wrong and ignorant for that issue (the reason is most likely because of React and JSX, like this reddit thread suggest https://www.reddit.com/r/reactjs/comments/jc8964/self_closing_tags_in_react/)

Hence, my vote goes to doing right thing and either ignore .html files (but *do* format .hbs, .gts, .gjs, etc.) or use Prettier plugin (only if it works perfectly).

2025-01-16 18:25 UTC, bertdeblock commented
fwiw, I'm not arguing that Prettier is doing the right thing. I agree that it's not according to the spec. I just feel that's a discussion for the Prettier project.

2025-01-16 18:26 UTC, SergeAstapov commented
maybe we should do RFC amendment to clarify this in RFC rather than in this thread? just a thought

2025-01-16 18:44 UTC, bertdeblock commented
Yeah, maybe it's safer to ignore html files for now then. Most projects only have 2 anyways.

2025-01-16 19:54 UTC, ef4 commented
> I'm now slightly worried that my RFC wasn't clear enough.
>The intention was to format all files Prettier supports, including (but not limited to) *.html and *.md files.

Looking at the RFC I think your intent is clear, but speaking for myself the thing I was paying attention to in the RFC is stopping running prettier inside eslint. That is, IMO, the most important motivation. Having the *option* of running prettier on more file types is only one of the benefits of that decision, and not nearly the most important one.

(Having prettier inside eslint is miserable. I've seen way too many developers reacting to red squiggles from the prettier eslint plugin, which is defeats the point of having prettier, which should free you to *stop* paying attention to formatting).

2025-01-17 07:36 UTC, bertdeblock commented
HTML changes are reverted, and `*.html` is added to the Prettier ignore file.
Ready for another review I think!

2025-01-17 12:13 UTC, SergeAstapov commented on blueprints/app/files/_js_eslint.config.mjs
> +import eslintConfigPrettier from 'eslint-config-prettier';
@bertdeblock why would we still need this if prettier runs outside of ESLint?

2025-01-17 12:15 UTC, SergeAstapov commented on blueprints/app/files/_js_eslint.config.mjs
> +import eslintConfigPrettier from 'eslint-config-prettier';
ah, right, so it's to disable any stylistic related rules in ESLint to avoid conflicts

2025-01-17 12:17 UTC, SergeAstapov approved these changes

2025-01-17 18:47 UTC, kategengler approved these changes

2025-01-17 19:18 UTC, ef4 approved these changes

2025-01-17 19:18 UTC, merged