Move ember-cli-build.js to tests/dummy for addons
ember-cli/ember-cli pull request #9366
Opened 2020-10-19 13:38 UTC by astronomersiva

Another attempt at addressing #7486 based on @rwjblue's suggestions during the recent Ember Contributors workshop. 

This is still a WIP and I just wanted to get some feedback on this before I go ahead and change the blueprints and add tests.

2020-10-19 13:56 UTC, rwjblue requested changes
Thanks for working on this!!! I left a few comments (hopefully helpful) inline, but we also need a few other things in order to land this:

* tests confirming that an arbitrary file can be used (e.g. `--build-file-path some/path/lol.js` should use `lol.js`)
* updates to the existing `--help` fixture tests to add the new option
* tests confirming that the fallback behavior to root level `ember-cli-build.js` works

2020-10-19 13:56 UTC, rwjblue commented on lib/commands/build.js
> +    { name: 'build-file-path', type: 'Path', default: 'tests/dummy/' },
Should probably the full path to the file (we want the path to the file, not the path to the directory that contains the file).

```suggestion
    { name: 'build-file-path', type: 'Path', default: 'tests/dummy/ember-cli-build.js' },
```

2020-10-19 13:56 UTC, rwjblue commented on lib/commands/serve.js
> +    { name: 'build-file-path', type: 'Path', default: 'tests/dummy/' },
Same as above 
```suggestion
    { name: 'build-file-path', type: 'Path', default: 'tests/dummy/ember-cli-build.js' },
```

2020-10-19 13:56 UTC, rwjblue commented on lib/commands/test.js
> +    { name: 'build-file-path', type: 'Path', default: 'tests/dummy/' },
```suggestion
    { name: 'build-file-path', type: 'Path', default: 'tests/dummy/ember-cli-build.js' },
```

2020-10-19 13:56 UTC, rwjblue commented on lib/models/builder.js
>    readBuildFile(path) {
Let's refactor this function to not take in the path argument here, it is more confusing overall than having the method itself control all of the logic (especially when the thing we get isn't the path to the file, its a directory path).

2020-10-19 13:56 UTC, rwjblue commented on lib/models/builder.js
>      throw new SilentError('No ember-cli-build.js found.');
I also don't really think that the `findBuildFile` utility is very helpful at all.

I think we should do this (modulo any silly mistakes I've made while prototyping...):

```js
  readBuildFile() {
    // Load the build file
    let buildFile;
    if (this.buildFilePath) {
      buildFile = require(this.buildFilePath);
    } else {
      let buildFilePath = findUp.sync('ember-cli-build.js', { cwd: this.project.root });
      
      buildFile = require(buildFilePath);
    }

    if (typeof buildFile !== 'function') {
      throw new SilentError('Could not find a valid ember-cli-build.js file.');
    }

    process.chdir(projectRoot);

    return buildFile({ project });
  }
```

And delete that utility file.

2020-10-19 20:44 UTC, astronomersiva commented
Thanks for the feedback @rwjblue!

I've done the following:

* Refactored the `readBuildFile` method to handle all the logic and removed the `findBuildFile` utility function.
* Updated the addon blueprints to generate the `ember-cli-build.js` at `tests/dummy` from now on.
* Added a test to ensure that backward compatibility is maintained in addons.
* Added a test to ensure that any file can be used along with the `build-file-path` argument.

I haven't updated the `--help` fixtures as I am not sure about how to update them. Is there anything like `jest --updateSnapshot` that I can use here for this?

2020-10-19 21:36 UTC, rwjblue commented on blueprints/addon/index.js
> +    );
Hmm, why do you need this? I would have expected that the `fileMap` just below here would have been updated to add:

```
'^ember-cli-build.js': 'tests/dummy/ember-cli-build.js'
```

2020-10-19 21:36 UTC, rwjblue commented on lib/models/builder.js
> +    }
Let's simplify, and ensure that the "magic" defaulting / find-up behavior only happens when a `--build-file-path` was **not** passed.

2020-10-19 21:36 UTC, rwjblue commented on tests/fixtures/addon/ember-cli-build-at-root/ember-cli-build.js
> +'use strict';
Can we test this with our custom fixturify-project test helper (instead of making more static fixture files)?

2020-10-19 21:37 UTC, rwjblue commented
> I haven't updated the --help fixtures as I am not sure about how to update them. Is there anything like jest --updateSnapshot that I can use here for this?

No, but I wish there was (or we'd migrate to using jest here).

2020-10-19 21:39 UTC, rwjblue commented on lib/models/builder.js
> +    }
Something like:

```js
let { buildFilePath } = this;
if (!buildFilePath) {
  let defaultBuildFilePath = project.isEmberCLIAddon()
    ? 'tests/dummy/ember-cli-build.js'
    : 'ember-cli-build.js';
  buildFilePath = path.join(project.root, defaultBuildFilePath);
  
  if (!fs.existsSync(buildFilePath)) {
    // backward compatibility for addons with `ember-cli-build.js` at project root.
    buildFilePath = findUp.sync('ember-cli-build.js', { cwd: project.root });
  }
}
```

2022-02-23 07:55 UTC, bertdeblock commented
Is this still something we want to pursue, knowing this won't be an issue with v2 addons?

2022-04-20 09:42 UTC, locks commented
I think @bertdeblock is correct and further time investment should go into ushering in the new embroider era 😁

2022-04-20 09:42 UTC, closed without merging