more livereload options
ember-cli/ember-cli pull request #9430
Opened 2021-01-14 08:28 UTC by lifeart

related issue: https://github.com/ember-cli/ember-cli-inject-live-reload/issues/150

2021-01-14 08:55 UTC, lifeart commented
looks like fixtures update requred @toranb @rwjblue any easy way to update it?
I could poke with https://github.com/suchipi/chai-jest-snapshot if needed

2021-01-14 09:08 UTC, ElenaSpb approved these changes

2021-01-14 09:50 UTC, sandstrom commented
Looks great! 🏅 

We've had to work around this by having our scripts write to `.ember-cli`, which isn't ideal. This would be much better.

2021-01-14 12:45 UTC, rwjblue requested changes
Overall seems good, thanks for working on it!

Some todos:

* needs tests 
* needs to add an error (early, when command options are parsed) if incompatible options are specified

2021-01-14 12:45 UTC, rwjblue commented on lib/commands/serve.js
> +      aliases: ['lrju'],
Let's remove the alias, I don't think this option is common enough to need an alias.

2021-01-14 12:45 UTC, rwjblue commented on lib/commands/serve.js
> +        'Stringified JSON object for LiveReload options. LiveReload supports a number of options for configuring websocket communication, including https, host, port, and others. See advanced example
I think the last part of this sentence should be removed ("see below for more info" doesn't seem right). Maybe replace it with a git.io link to the README where it is listed?

2021-01-14 13:09 UTC, lifeart commented
@rwjblue could you help with fixtures updated approach? Should I somehow regenrate existing one? (is so - I have no idea how to update it), or move touched checks to `chai-jest-snapshot`?

2021-01-14 13:10 UTC, rwjblue commented
What fixtures?

2021-01-14 13:20 UTC, lifeart commented
> What fixtures?
for example: tests\fixtures\help\help.txt

![image](https://user-images.githubusercontent.com/1360552/104595948-58c66180-5684-11eb-9827-c3b14bd3f4e3.png)


CI is failing on it, but I don't know how to update it in a right way

2021-01-14 14:49 UTC, rwjblue commented
Ya, I'd love to make those snapshots. Updating them is mega painful everytime 😩. If you have the time/energy, I'd love a separate PR that migrates those to use snapshots (then we can update those new snapshots in this PR).

2021-10-08 10:38 UTC, lifeart commented
@rwjblue looks like it's alive now

2024-10-31 15:58 UTC, bertdeblock commented
Going to close for now, due to inactivity.

2024-10-31 15:58 UTC, closed without merging