Add --embroider as an option for new and init
ember-cli/ember-cli pull request #9454
Opened 2021-02-23 22:55 UTC by thoov

Enables --embroider along with EMBER_CLI_EMBROIDER to default the build to embroider.

2021-02-23 23:30 UTC, rwjblue requested changes
Overall 👍👍, I think we need to add a description for the flag (so the help output has some conceptual explanation of what its for).

2021-02-23 23:30 UTC, rwjblue commented on lib/commands/new.js
> +    { name: 'embroider', type: Boolean, default: false },
Can you add a description here too?

2021-02-23 23:30 UTC, rwjblue commented on lib/commands/init.js
> +    { name: 'embroider', type: Boolean, default: false },
Can you add a description for the flag?

2021-02-24 04:54 UTC, thoov commented
@rwjblue should be good now

2021-02-24 19:54 UTC, rwjblue approved these changes

2021-02-24 19:54 UTC, merged