Drop Node 10 support in blueprint engine spec
ember-cli/ember-cli pull request #9565
Opened 2021-06-03 19:07 UTC by elwayman02

This appears to have been missed in #9530

cc: @rwjblue

2021-06-03 19:10 UTC, rwjblue requested changes

2021-06-03 19:10 UTC, rwjblue commented on blueprints/app/files/package.json
> +    "node": ">= 12"
Should be 
```suggestion
    "node": "12.* || 14.* || >= 16"
```

2021-06-03 19:26 UTC, elwayman02 commented
@rwjblue I updated the fixtures to match the new engine support you suggested. Thanks!

2021-06-03 21:35 UTC, elwayman02 commented
@rwjblue are you able to restart these builds? The failure looks like a flaky test, but I don't have access to re-run them.

2021-06-05 18:01 UTC, rwjblue commented
Restarted

2021-06-08 23:52 UTC, elwayman02 commented
Failures appear flaky again @rwjblue :(

2021-06-11 13:46 UTC, rwjblue commented
The Embroider failures are:

```
not ok 1 Chrome 91.0 - [undefined ms] - Global error: Uncaught TypeError: Cannot read property 'prototype' of undefined at webpack://some-cool-app/../node-E3gpVVB0.tmp/node_modules/@ember-data/debug/setup.js?, line 20
    ---
        browser log: |
            testContext: [object Object]
            ERROR: Uncaught TypeError: Cannot read property 'prototype' of undefined at webpack://some-cool-app/../node-E3gpVVB0.tmp/node_modules/@ember-data/debug/setup.js?, line 20
            
    ...

```

Which is what @thoov reported in https://github.com/embroider-build/embroider/issues/826, definitely unrelated to these changes.

2021-06-11 13:47 UTC, merged

2025-02-13 20:46 UTC, 1atAlcone approved these changes
### - [ ] -

2025-02-13 20:46 UTC, 1atAlcone approved these changes

2025-02-13 20:51 UTC, 1atAlcone commented
_hi 👋_